# Generated by Django 5.2.4 on 2025-07-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='subject name')),
            ],
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ebooks/images/', verbose_name='image')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('part', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='part')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='grade')),
                ('related_studies', models.ManyToManyField(blank=True, to='ebooks.ebook', verbose_name='related studies')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebooks.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'e-book',
                'verbose_name_plural': 'e-books',
            },
        ),
        migrations.CreateModel(
            name='EBookAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('unit', 'Unit audio'), ('page', 'Page audio')], max_length=10, verbose_name='audio type')),
                ('audio_file', models.FileField(upload_to='ebooks/audios/', verbose_name='audio file')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='ebooks.ebook')),
            ],
            options={
                'verbose_name': 'e-book audio',
                'verbose_name_plural': 'e-book audios',
            },
        ),
    ]
