# Generated by Django 5.2.4 on 2025-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный идентификатор для URL', max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
