# Generated by Django 5.2.4 on 2025-07-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_ebook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Уникальный идентификатор для URL'),
        ),
    ]
