# Generated by Django 5.2.4 on 2025-07-09 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_alter_ebook_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebookaudio',
            options={'ordering': ['ebook', 'page', 'audio_type'], 'verbose_name': 'e‑book audio', 'verbose_name_plural': 'e‑book audios'},
        ),
        migrations.AddField(
            model_name='ebookaudio',
            name='audio_label',
            field=models.CharField(blank=True, help_text='e.g. “Unit\u202f1 – Track\u202f3”', max_length=255, verbose_name='audio label'),
        ),
        migrations.AddField(
            model_name='ebookaudio',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='ebookaudio',
            name='ebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='ebooks.ebook', verbose_name='e‑book'),
        ),
    ]
