# Generated by Django 5.2.4 on 2025-07-09 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_alter_ebookaudio_options_ebookaudio_audio_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ebookaudio',
            options={'ordering': ['ebook', 'page', 'audio_type'], 'verbose_name': 'Аудиофайл', 'verbose_name_plural': 'Аудиофайлы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='subject',
        ),
        migrations.AddField(
            model_name='ebook',
            name='for_whom',
            field=models.CharField(choices=[('textbook', 'Учебник'), ('reference', 'Справочник'), ('supplementary', 'Дополнительные материалы'), ('other', 'Другие')], default='textbook', max_length=20, verbose_name='Для кого'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ebooks/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='part',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Часть'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='related_studies',
            field=models.ManyToManyField(blank=True, to='ebooks.ebook', verbose_name='Связанные учебные программы'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='ebookaudio',
            name='audio_file',
            field=models.FileField(upload_to='ebooks/audios/', verbose_name='Аудиофайл'),
        ),
        migrations.AlterField(
            model_name='ebookaudio',
            name='audio_label',
            field=models.CharField(blank=True, help_text='например, "Unit 1 – Track 3"', max_length=255, verbose_name='Метка аудио'),
        ),
        migrations.AlterField(
            model_name='ebookaudio',
            name='audio_type',
            field=models.CharField(choices=[('basic', 'Основное'), ('repetition', 'Повторение')], max_length=10, verbose_name='Тип аудио'),
        ),
        migrations.AlterField(
            model_name='ebookaudio',
            name='ebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='ebooks.ebook', verbose_name='Учебник'),
        ),
        migrations.AlterField(
            model_name='ebookaudio',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название предмета'),
        ),
    ]
