# Generated by Django 5.2.4 on 2025-07-09 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0005_alter_ebook_options_alter_ebookaudio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebook',
            options={'ordering': ['title'], 'verbose_name': 'Электронная книга', 'verbose_name_plural': 'Электронные книги'},
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='for_whom',
        ),
        migrations.AddField(
            model_name='ebook',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebooks.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebook',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ebooks/images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='part',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Часть'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebook',
            name='related_studies',
            field=models.ManyToManyField(blank=True, to='ebooks.ebook', verbose_name='Связанные материалы'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Уникальный идентификатор (slug)'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Год издания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
    ]
