# Generated by Django 5.2.4 on 2025-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0006_alter_ebook_options_remove_ebook_for_whom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='grade',
            field=models.IntegerField(default=1, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название электронной книги'),
        ),
    ]
